version: '3'
services:
  vault-etcd:
    image: 'vault:latest'
    ports:
      - "8200:8200"
    volumes:
      - .docker/volumes/vault-etcd/file:/vault/file:rw
      - .docker/volumes/vault-etcd/config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    entrypoint:
      - vault
      - server
      - -config=/vault/config/vault.hcl
    depends_on:
      - etcd0
      - etcd1
      - etcd2
  etcd0:
    image: 'quay.io/coreos/etcd'
    ports:
      - 2379
    volumes:
      - etcd0:/var/etcd/data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /var/etcd/data
      - -advertise-client-urls
      - http://etcd0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd0:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  etcd1:
    image: 'quay.io/coreos/etcd'
    ports:
      - 2379
    volumes:
      - etcd1:/var/etcd/data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd1
      - --data-dir
      - /var/etcd/data
      - -advertise-client-urls
      - http://etcd1:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
  etcd2:
    image: 'quay.io/coreos/etcd'
    ports:
      - 2379
    volumes:
      - etcd2:/var/etcd/data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd2
      - --data-dir
      - /var/etcd/data
      - -advertise-client-urls
      - http://etcd2:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd2:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
volumes:
  etcd0:
  etcd1:
  etcd2:
